# Test NasmX86 2022-01-01 at 19:09:58

name: Test

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'main'

    - name: Download other repos
      run: |
        curl -sL https://github.com/philiprbrenan/NasmX86/archive/refs/heads/main.zip       > NasmX86.zip
        curl -sL https://github.com/philiprbrenan/DataTableText/archive/refs/heads/main.zip > DataTableText.zip
        curl -sL https://github.com/philiprbrenan/GitHubCrud/archive/refs/heads/main.zip    > GitHubCrud.zip
        curl -sL https://github.com/philiprbrenan/AsmC/archive/refs/heads/main.zip          > AsmC.zip
        ls -la NasmX86.zip DataTableText.zip GitHubCrud.zip AsmC.zip
        tree
        unzip NasmX86
        unzip DataTableText
        unzip GitHubCrud
        unzip AsmC.zip
        tree
        cp -R NasmX86-main/* .
        cp -R DataTableText-main/* .
        cp -R GitHubCrud-main/* .
        cp -R AsmC-main/* .
        tree

    - name: Install Test::Most
      run: |
        sudo cpan install -T Test::Most

    - name: Install Nasm
      run: |
        sudo apt-get install -y nasm

    - name: Install Intel Sde
      run: |
        tar -xf sde.tar.bz2
        mv sde-external-8.63.0-2021-01-18-lin/ sde/
        tree

    - name: Test
      run: |
        perl -Ilib lib/Nasm/X86.pm
