# Test NasmX86 2022-07-07 at 06:07:44

name: Test

on:
  push

jobs:
  test01:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'main'

    - name: Download other repos
      run: |
        curl -sL https://github.com/philiprbrenan/NasmX86/archive/refs/heads/main.zip       > NasmX86.zip
        curl -sL https://github.com/philiprbrenan/DataTableText/archive/refs/heads/main.zip > DataTableText.zip
        curl -sL https://github.com/philiprbrenan/GitHubCrud/archive/refs/heads/main.zip    > GitHubCrud.zip
        curl -sL https://github.com/philiprbrenan/AsmC/archive/refs/heads/main.zip          > AsmC.zip
        ls -la NasmX86.zip DataTableText.zip GitHubCrud.zip AsmC.zip
        tree
        unzip NasmX86
        unzip DataTableText
        unzip GitHubCrud
        unzip AsmC.zip
        tree
        cp -R NasmX86-main/* .
        cp -R DataTableText-main/* .
        cp -R GitHubCrud-main/* .
        cp -R AsmC-main/* .
        tree

    - name: avx
      run: |
        perl -e'my $f = {map {$_=>1} grep {/avx/} map {split /\s+/} grep {/flags/} split /\n/, qx(cat /proc/cpuinfo)}; print join q( ), sort keys %$f; print qq(\n)';
        #printenv

    - name: Install Test::Most
      run: |
        sudo cpan install -T Test::Most

    - name: Install Intel Sde
      run: |
        tar -xf sde.tar.bz2
        mv sde-external-8.63.0-2021-01-18-lin/ sde/
        tree

    - name: Install Nasm
      run: |
        sudo apt-get install -y nasm

    - name: Test1
      run: |
        echo $?

    - name: Result1
      run: |
        cat zzzStatus.txt

  test02:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'main'

    - name: Download other repos
      run: |
        curl -sL https://github.com/philiprbrenan/NasmX86/archive/refs/heads/main.zip       > NasmX86.zip
        curl -sL https://github.com/philiprbrenan/DataTableText/archive/refs/heads/main.zip > DataTableText.zip
        curl -sL https://github.com/philiprbrenan/GitHubCrud/archive/refs/heads/main.zip    > GitHubCrud.zip
        curl -sL https://github.com/philiprbrenan/AsmC/archive/refs/heads/main.zip          > AsmC.zip
        ls -la NasmX86.zip DataTableText.zip GitHubCrud.zip AsmC.zip
        tree
        unzip NasmX86
        unzip DataTableText
        unzip GitHubCrud
        unzip AsmC.zip
        tree
        cp -R NasmX86-main/* .
        cp -R DataTableText-main/* .
        cp -R GitHubCrud-main/* .
        cp -R AsmC-main/* .
        tree

    - name: avx
      run: |
        perl -e'my $f = {map {$_=>1} grep {/avx/} map {split /\s+/} grep {/flags/} split /\n/, qx(cat /proc/cpuinfo)}; print join q( ), sort keys %$f; print qq(\n)';
        #printenv

    - name: Install Test::Most
      run: |
        sudo cpan install -T Test::Most

    - name: Install Intel Sde
      run: |
        tar -xf sde.tar.bz2
        mv sde-external-8.63.0-2021-01-18-lin/ sde/
        tree

    - name: Install Nasm
      run: |
        sudo apt-get install -y nasm

    - name: Test2
      run: |
        echo $?

    - name: Result2
      run: |
        cat zzzStatus.txt

  test03:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'main'

    - name: Download other repos
      run: |
        curl -sL https://github.com/philiprbrenan/NasmX86/archive/refs/heads/main.zip       > NasmX86.zip
        curl -sL https://github.com/philiprbrenan/DataTableText/archive/refs/heads/main.zip > DataTableText.zip
        curl -sL https://github.com/philiprbrenan/GitHubCrud/archive/refs/heads/main.zip    > GitHubCrud.zip
        curl -sL https://github.com/philiprbrenan/AsmC/archive/refs/heads/main.zip          > AsmC.zip
        ls -la NasmX86.zip DataTableText.zip GitHubCrud.zip AsmC.zip
        tree
        unzip NasmX86
        unzip DataTableText
        unzip GitHubCrud
        unzip AsmC.zip
        tree
        cp -R NasmX86-main/* .
        cp -R DataTableText-main/* .
        cp -R GitHubCrud-main/* .
        cp -R AsmC-main/* .
        tree

    - name: avx
      run: |
        perl -e'my $f = {map {$_=>1} grep {/avx/} map {split /\s+/} grep {/flags/} split /\n/, qx(cat /proc/cpuinfo)}; print join q( ), sort keys %$f; print qq(\n)';
        #printenv

    - name: Install Test::Most
      run: |
        sudo cpan install -T Test::Most

    - name: Install Intel Sde
      run: |
        tar -xf sde.tar.bz2
        mv sde-external-8.63.0-2021-01-18-lin/ sde/
        tree

    - name: Install Nasm
      run: |
        sudo apt-get install -y nasm

    - name: Test3
      run: |
        echo $?

    - name: Result3
      run: |
        cat zzzStatus.txt

  test04:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'main'

    - name: Download other repos
      run: |
        curl -sL https://github.com/philiprbrenan/NasmX86/archive/refs/heads/main.zip       > NasmX86.zip
        curl -sL https://github.com/philiprbrenan/DataTableText/archive/refs/heads/main.zip > DataTableText.zip
        curl -sL https://github.com/philiprbrenan/GitHubCrud/archive/refs/heads/main.zip    > GitHubCrud.zip
        curl -sL https://github.com/philiprbrenan/AsmC/archive/refs/heads/main.zip          > AsmC.zip
        ls -la NasmX86.zip DataTableText.zip GitHubCrud.zip AsmC.zip
        tree
        unzip NasmX86
        unzip DataTableText
        unzip GitHubCrud
        unzip AsmC.zip
        tree
        cp -R NasmX86-main/* .
        cp -R DataTableText-main/* .
        cp -R GitHubCrud-main/* .
        cp -R AsmC-main/* .
        tree

    - name: avx
      run: |
        perl -e'my $f = {map {$_=>1} grep {/avx/} map {split /\s+/} grep {/flags/} split /\n/, qx(cat /proc/cpuinfo)}; print join q( ), sort keys %$f; print qq(\n)';
        #printenv

    - name: Install Test::Most
      run: |
        sudo cpan install -T Test::Most

    - name: Install Intel Sde
      run: |
        tar -xf sde.tar.bz2
        mv sde-external-8.63.0-2021-01-18-lin/ sde/
        tree

    - name: Install Nasm
      run: |
        sudo apt-get install -y nasm

    - name: Test4
      run: |
        echo $?

    - name: Result4
      run: |
        cat zzzStatus.txt

  test05:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'main'

    - name: Download other repos
      run: |
        curl -sL https://github.com/philiprbrenan/NasmX86/archive/refs/heads/main.zip       > NasmX86.zip
        curl -sL https://github.com/philiprbrenan/DataTableText/archive/refs/heads/main.zip > DataTableText.zip
        curl -sL https://github.com/philiprbrenan/GitHubCrud/archive/refs/heads/main.zip    > GitHubCrud.zip
        curl -sL https://github.com/philiprbrenan/AsmC/archive/refs/heads/main.zip          > AsmC.zip
        ls -la NasmX86.zip DataTableText.zip GitHubCrud.zip AsmC.zip
        tree
        unzip NasmX86
        unzip DataTableText
        unzip GitHubCrud
        unzip AsmC.zip
        tree
        cp -R NasmX86-main/* .
        cp -R DataTableText-main/* .
        cp -R GitHubCrud-main/* .
        cp -R AsmC-main/* .
        tree

    - name: avx
      run: |
        perl -e'my $f = {map {$_=>1} grep {/avx/} map {split /\s+/} grep {/flags/} split /\n/, qx(cat /proc/cpuinfo)}; print join q( ), sort keys %$f; print qq(\n)';
        #printenv

    - name: Install Test::Most
      run: |
        sudo cpan install -T Test::Most

    - name: Install Intel Sde
      run: |
        tar -xf sde.tar.bz2
        mv sde-external-8.63.0-2021-01-18-lin/ sde/
        tree

    - name: Install Nasm
      run: |
        sudo apt-get install -y nasm

    - name: Test5
      run: |
        echo $?

    - name: Result5
      run: |
        cat zzzStatus.txt

  test06:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'main'

    - name: Download other repos
      run: |
        curl -sL https://github.com/philiprbrenan/NasmX86/archive/refs/heads/main.zip       > NasmX86.zip
        curl -sL https://github.com/philiprbrenan/DataTableText/archive/refs/heads/main.zip > DataTableText.zip
        curl -sL https://github.com/philiprbrenan/GitHubCrud/archive/refs/heads/main.zip    > GitHubCrud.zip
        curl -sL https://github.com/philiprbrenan/AsmC/archive/refs/heads/main.zip          > AsmC.zip
        ls -la NasmX86.zip DataTableText.zip GitHubCrud.zip AsmC.zip
        tree
        unzip NasmX86
        unzip DataTableText
        unzip GitHubCrud
        unzip AsmC.zip
        tree
        cp -R NasmX86-main/* .
        cp -R DataTableText-main/* .
        cp -R GitHubCrud-main/* .
        cp -R AsmC-main/* .
        tree

    - name: avx
      run: |
        perl -e'my $f = {map {$_=>1} grep {/avx/} map {split /\s+/} grep {/flags/} split /\n/, qx(cat /proc/cpuinfo)}; print join q( ), sort keys %$f; print qq(\n)';
        #printenv

    - name: Install Test::Most
      run: |
        sudo cpan install -T Test::Most

    - name: Install Intel Sde
      run: |
        tar -xf sde.tar.bz2
        mv sde-external-8.63.0-2021-01-18-lin/ sde/
        tree

    - name: Install Nasm
      run: |
        sudo apt-get install -y nasm

    - name: Test6
      run: |
        echo $?

    - name: Result6
      run: |
        cat zzzStatus.txt

  test07:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'main'

    - name: Download other repos
      run: |
        curl -sL https://github.com/philiprbrenan/NasmX86/archive/refs/heads/main.zip       > NasmX86.zip
        curl -sL https://github.com/philiprbrenan/DataTableText/archive/refs/heads/main.zip > DataTableText.zip
        curl -sL https://github.com/philiprbrenan/GitHubCrud/archive/refs/heads/main.zip    > GitHubCrud.zip
        curl -sL https://github.com/philiprbrenan/AsmC/archive/refs/heads/main.zip          > AsmC.zip
        ls -la NasmX86.zip DataTableText.zip GitHubCrud.zip AsmC.zip
        tree
        unzip NasmX86
        unzip DataTableText
        unzip GitHubCrud
        unzip AsmC.zip
        tree
        cp -R NasmX86-main/* .
        cp -R DataTableText-main/* .
        cp -R GitHubCrud-main/* .
        cp -R AsmC-main/* .
        tree

    - name: avx
      run: |
        perl -e'my $f = {map {$_=>1} grep {/avx/} map {split /\s+/} grep {/flags/} split /\n/, qx(cat /proc/cpuinfo)}; print join q( ), sort keys %$f; print qq(\n)';
        #printenv

    - name: Install Test::Most
      run: |
        sudo cpan install -T Test::Most

    - name: Install Intel Sde
      run: |
        tar -xf sde.tar.bz2
        mv sde-external-8.63.0-2021-01-18-lin/ sde/
        tree

    - name: Install Nasm
      run: |
        sudo apt-get install -y nasm

    - name: Test7
      run: |
        echo $?

    - name: Result7
      run: |
        cat zzzStatus.txt

  test08:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'main'

    - name: Download other repos
      run: |
        curl -sL https://github.com/philiprbrenan/NasmX86/archive/refs/heads/main.zip       > NasmX86.zip
        curl -sL https://github.com/philiprbrenan/DataTableText/archive/refs/heads/main.zip > DataTableText.zip
        curl -sL https://github.com/philiprbrenan/GitHubCrud/archive/refs/heads/main.zip    > GitHubCrud.zip
        curl -sL https://github.com/philiprbrenan/AsmC/archive/refs/heads/main.zip          > AsmC.zip
        ls -la NasmX86.zip DataTableText.zip GitHubCrud.zip AsmC.zip
        tree
        unzip NasmX86
        unzip DataTableText
        unzip GitHubCrud
        unzip AsmC.zip
        tree
        cp -R NasmX86-main/* .
        cp -R DataTableText-main/* .
        cp -R GitHubCrud-main/* .
        cp -R AsmC-main/* .
        tree

    - name: avx
      run: |
        perl -e'my $f = {map {$_=>1} grep {/avx/} map {split /\s+/} grep {/flags/} split /\n/, qx(cat /proc/cpuinfo)}; print join q( ), sort keys %$f; print qq(\n)';
        #printenv

    - name: Install Test::Most
      run: |
        sudo cpan install -T Test::Most

    - name: Install Intel Sde
      run: |
        tar -xf sde.tar.bz2
        mv sde-external-8.63.0-2021-01-18-lin/ sde/
        tree

    - name: Install Nasm
      run: |
        sudo apt-get install -y nasm

    - name: Test8
      run: |
        echo $?

    - name: Result8
      run: |
        cat zzzStatus.txt

  test09:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'main'

    - name: Download other repos
      run: |
        curl -sL https://github.com/philiprbrenan/NasmX86/archive/refs/heads/main.zip       > NasmX86.zip
        curl -sL https://github.com/philiprbrenan/DataTableText/archive/refs/heads/main.zip > DataTableText.zip
        curl -sL https://github.com/philiprbrenan/GitHubCrud/archive/refs/heads/main.zip    > GitHubCrud.zip
        curl -sL https://github.com/philiprbrenan/AsmC/archive/refs/heads/main.zip          > AsmC.zip
        ls -la NasmX86.zip DataTableText.zip GitHubCrud.zip AsmC.zip
        tree
        unzip NasmX86
        unzip DataTableText
        unzip GitHubCrud
        unzip AsmC.zip
        tree
        cp -R NasmX86-main/* .
        cp -R DataTableText-main/* .
        cp -R GitHubCrud-main/* .
        cp -R AsmC-main/* .
        tree

    - name: avx
      run: |
        perl -e'my $f = {map {$_=>1} grep {/avx/} map {split /\s+/} grep {/flags/} split /\n/, qx(cat /proc/cpuinfo)}; print join q( ), sort keys %$f; print qq(\n)';
        #printenv

    - name: Install Test::Most
      run: |
        sudo cpan install -T Test::Most

    - name: Install Intel Sde
      run: |
        tar -xf sde.tar.bz2
        mv sde-external-8.63.0-2021-01-18-lin/ sde/
        tree

    - name: Install Nasm
      run: |
        sudo apt-get install -y nasm

    - name: Test9
      run: |
        echo $?

    - name: Result9
      run: |
        cat zzzStatus.txt

  test10:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'main'

    - name: Download other repos
      run: |
        curl -sL https://github.com/philiprbrenan/NasmX86/archive/refs/heads/main.zip       > NasmX86.zip
        curl -sL https://github.com/philiprbrenan/DataTableText/archive/refs/heads/main.zip > DataTableText.zip
        curl -sL https://github.com/philiprbrenan/GitHubCrud/archive/refs/heads/main.zip    > GitHubCrud.zip
        curl -sL https://github.com/philiprbrenan/AsmC/archive/refs/heads/main.zip          > AsmC.zip
        ls -la NasmX86.zip DataTableText.zip GitHubCrud.zip AsmC.zip
        tree
        unzip NasmX86
        unzip DataTableText
        unzip GitHubCrud
        unzip AsmC.zip
        tree
        cp -R NasmX86-main/* .
        cp -R DataTableText-main/* .
        cp -R GitHubCrud-main/* .
        cp -R AsmC-main/* .
        tree

    - name: avx
      run: |
        perl -e'my $f = {map {$_=>1} grep {/avx/} map {split /\s+/} grep {/flags/} split /\n/, qx(cat /proc/cpuinfo)}; print join q( ), sort keys %$f; print qq(\n)';
        #printenv

    - name: Install Test::Most
      run: |
        sudo cpan install -T Test::Most

    - name: Install Intel Sde
      run: |
        tar -xf sde.tar.bz2
        mv sde-external-8.63.0-2021-01-18-lin/ sde/
        tree

    - name: Install Nasm
      run: |
        sudo apt-get install -y nasm

    - name: Test10
      run: |
        echo $?

    - name: Result10
      run: |
        cat zzzStatus.txt

  test11:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'main'

    - name: Download other repos
      run: |
        curl -sL https://github.com/philiprbrenan/NasmX86/archive/refs/heads/main.zip       > NasmX86.zip
        curl -sL https://github.com/philiprbrenan/DataTableText/archive/refs/heads/main.zip > DataTableText.zip
        curl -sL https://github.com/philiprbrenan/GitHubCrud/archive/refs/heads/main.zip    > GitHubCrud.zip
        curl -sL https://github.com/philiprbrenan/AsmC/archive/refs/heads/main.zip          > AsmC.zip
        ls -la NasmX86.zip DataTableText.zip GitHubCrud.zip AsmC.zip
        tree
        unzip NasmX86
        unzip DataTableText
        unzip GitHubCrud
        unzip AsmC.zip
        tree
        cp -R NasmX86-main/* .
        cp -R DataTableText-main/* .
        cp -R GitHubCrud-main/* .
        cp -R AsmC-main/* .
        tree

    - name: avx
      run: |
        perl -e'my $f = {map {$_=>1} grep {/avx/} map {split /\s+/} grep {/flags/} split /\n/, qx(cat /proc/cpuinfo)}; print join q( ), sort keys %$f; print qq(\n)';
        #printenv

    - name: Install Test::Most
      run: |
        sudo cpan install -T Test::Most

    - name: Install Intel Sde
      run: |
        tar -xf sde.tar.bz2
        mv sde-external-8.63.0-2021-01-18-lin/ sde/
        tree

    - name: Install Nasm
      run: |
        sudo apt-get install -y nasm

    - name: Test11
      run: |
        echo $?

    - name: Result11
      run: |
        cat zzzStatus.txt

  test12:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'main'

    - name: Download other repos
      run: |
        curl -sL https://github.com/philiprbrenan/NasmX86/archive/refs/heads/main.zip       > NasmX86.zip
        curl -sL https://github.com/philiprbrenan/DataTableText/archive/refs/heads/main.zip > DataTableText.zip
        curl -sL https://github.com/philiprbrenan/GitHubCrud/archive/refs/heads/main.zip    > GitHubCrud.zip
        curl -sL https://github.com/philiprbrenan/AsmC/archive/refs/heads/main.zip          > AsmC.zip
        ls -la NasmX86.zip DataTableText.zip GitHubCrud.zip AsmC.zip
        tree
        unzip NasmX86
        unzip DataTableText
        unzip GitHubCrud
        unzip AsmC.zip
        tree
        cp -R NasmX86-main/* .
        cp -R DataTableText-main/* .
        cp -R GitHubCrud-main/* .
        cp -R AsmC-main/* .
        tree

    - name: avx
      run: |
        perl -e'my $f = {map {$_=>1} grep {/avx/} map {split /\s+/} grep {/flags/} split /\n/, qx(cat /proc/cpuinfo)}; print join q( ), sort keys %$f; print qq(\n)';
        #printenv

    - name: Install Test::Most
      run: |
        sudo cpan install -T Test::Most

    - name: Install Intel Sde
      run: |
        tar -xf sde.tar.bz2
        mv sde-external-8.63.0-2021-01-18-lin/ sde/
        tree

    - name: Install Nasm
      run: |
        sudo apt-get install -y nasm

    - name: Test12
      run: |
        echo $?

    - name: Result12
      run: |
        cat zzzStatus.txt
